version: '2'
services:
  hipster6-app:
    image: hipster6
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://hipster6-mariadb:3306/hipster6
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
    ports:
      - 8080:8080
  hipster6-mariadb:
    extends:
      file: mariadb.yml
      service: hipster6-mariadb
